In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_2014 = pd.read_csv('./new_data/2014_US_exchange.csv', index_col=0)
df_2015 = pd.read_csv('./new_data/2015_US_exchange.csv', index_col=0)
df_2016 = pd.read_csv('./new_data/2016_US_exchange.csv', index_col=0)
df_2017 = pd.read_csv('./new_data/2017_US_exchange.csv', index_col=0)
df_2018 = pd.read_csv('./new_data/2018_US_exchange.csv', index_col=0)

In [3]:
df_2014.rename(columns={"2015 PRICE VAR [%]": "PRICE_VAR"},inplace=True)
df_2015.rename(columns={"2016 PRICE VAR [%]": "PRICE_VAR"},inplace=True)
df_2016.rename(columns={"2017 PRICE VAR [%]": "PRICE_VAR"},inplace=True)
df_2017.rename(columns={"2018 PRICE VAR [%]": "PRICE_VAR"},inplace=True)
df_2018.rename(columns={"2019 PRICE VAR [%]": "PRICE_VAR"},inplace=True)

In [4]:
# Rename the train, validation and test sets
train = pd.concat([df_2014, df_2015, df_2016])
val = df_2017
test = df_2018

In [5]:
train.drop(['PRICE_VAR'], axis=1, inplace=True)

In [6]:
train.head(5)

Symbol       Revenue  Revenue Growth  Cost of Revenue  Gross Profit  \
0     PG  7.440100e+10         -0.0713     3.903000e+10  3.537100e+10   
1   VIPS  3.734148e+09          1.1737     2.805625e+09  9.285226e+08   
2     KR  9.837500e+10          0.0182     7.813800e+10  2.023700e+10   
3    RAD  2.552641e+10          0.0053     1.820268e+10  7.323734e+09   
4    GIS  1.790960e+10          0.0076     1.153980e+10  6.369800e+09   

   R&D Expenses  SG&A Expense  Operating Expenses  Operating Income  \
0  0.000000e+00  2.146100e+10        2.146100e+10      1.391000e+10   
1  1.083303e+08  3.441414e+08        7.939267e+08      1.345959e+08   
2  0.000000e+00  1.519600e+10        1.751200e+10      2.725000e+09   
3  0.000000e+00  6.561162e+09        6.586482e+09      7.372520e+08   
4  0.000000e+00  3.474300e+09        3.412400e+09      2.957400e+09   

   Interest Expense  ...  3Y Dividend per Share Growth (per Share)  \
0      7.090000e+08  ...                                    0.0751   
1      1.214869e+07  ...                                       NaN   
2      4.430000e+08  ...                                    0.1633   
3      4.245910e+08  ...                                    0.0000   
4      3.024000e+08  ...                                    0.1144   

   Receivables growth  Inventory Growth  Asset Growth  \
0             -0.0187           -0.0217        0.0359   
1                 NaN               NaN           NaN   
2              0.0618            0.0981        0.1886   
3              0.0211           -0.0510       -0.0189   
4              0.0257            0.0090        0.0215   

   Book Value per Share Growth  Debt Growth  R&D Expense Growth  \
0                       0.0316       0.1228              0.0000   
1                          NaN          NaN              1.6484   
2                       0.3268       0.2738              0.0000   
3                       0.1963      -0.0458              0.0000   
4                       0.0274       0.1025              0.0000   

   SG&A Expenses Growth              Sector  Class  
0               -0.1746  Consumer Defensive      0  
1                1.7313  Consumer Defensive      0  
2                0.0234  Consumer Defensive      1  
3               -0.0060  Consumer Defensive      1  
4               -0.0220  Consumer Defensive      1  

[5 rows x 224 columns]

In [7]:
train.replace([np.inf, -np.inf], np.nan)
train.fillna(0, inplace=True)
val.replace([np.inf, -np.inf], np.nan)
val.fillna(0, inplace=True)
test.replace([np.inf, -np.inf], np.nan)
test.fillna(0, inplace=True)

In [8]:
train_features = train.iloc[:, 1:-2]
train_label = train.iloc[:, -1]
val.drop(['PRICE_VAR'], axis=1, inplace=True)
val_features = val.iloc[:, 1:-2]
val_label = val.iloc[:, -1]
test.drop(['PRICE_VAR'], axis=1, inplace=True)
test_features = test.iloc[:, 1:-2]
test_label = test.iloc[:, -1]

In [9]:
train_features.head(5)

Revenue  Revenue Growth  Cost of Revenue  Gross Profit  R&D Expenses  \
0  7.440100e+10         -0.0713     3.903000e+10  3.537100e+10  0.000000e+00   
1  3.734148e+09          1.1737     2.805625e+09  9.285226e+08  1.083303e+08   
2  9.837500e+10          0.0182     7.813800e+10  2.023700e+10  0.000000e+00   
3  2.552641e+10          0.0053     1.820268e+10  7.323734e+09  0.000000e+00   
4  1.790960e+10          0.0076     1.153980e+10  6.369800e+09  0.000000e+00   

   SG&A Expense  Operating Expenses  Operating Income  Interest Expense  \
0  2.146100e+10        2.146100e+10      1.391000e+10      7.090000e+08   
1  3.441414e+08        7.939267e+08      1.345959e+08      1.214869e+07   
2  1.519600e+10        1.751200e+10      2.725000e+09      4.430000e+08   
3  6.561162e+09        6.586482e+09      7.372520e+08      4.245910e+08   
4  3.474300e+09        3.412400e+09      2.957400e+09      3.024000e+08   

   Earnings before Tax  ...  10Y Dividend per Share Growth (per Share)  \
0         1.449400e+10  ...                                     0.1013   
1         1.753823e+08  ...                                     0.0000   
2         2.270000e+09  ...                                     0.0000   
3         2.502180e+08  ...                                     0.0000   
4         2.707700e+09  ...                                     0.1092   

   5Y Dividend per Share Growth (per Share)  \
0                                    0.0834   
1                                    0.0000   
2                                    0.1215   
3                                    0.0000   
4                                    0.1250   

   3Y Dividend per Share Growth (per Share)  Receivables growth  \
0                                    0.0751             -0.0187   
1                                    0.0000              0.0000   
2                                    0.1633              0.0618   
3                                    0.0000              0.0211   
4                                    0.1144              0.0257   

   Inventory Growth  Asset Growth  Book Value per Share Growth  Debt Growth  \
0           -0.0217        0.0359                       0.0316       0.1228   
1            0.0000        0.0000                       0.0000       0.0000   
2            0.0981        0.1886                       0.3268       0.2738   
3           -0.0510       -0.0189                       0.1963      -0.0458   
4            0.0090        0.0215                       0.0274       0.1025   

   R&D Expense Growth  SG&A Expenses Growth  
0              0.0000               -0.1746  
1              1.6484                1.7313  
2              0.0000                0.0234  
3              0.0000               -0.0060  
4              0.0000               -0.0220  

[5 rows x 221 columns]

In [10]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

In [11]:
# test linear SVM
linear_model = make_pipeline(StandardScaler(), SVC(kernel='linear'))
linear_model.fit(train_features, train_label)
# Prediction
train_pred = linear_model.predict(train_features)
train_acc = accuracy_score(train_label, train_pred)
train_f1 = f1_score(train_label, train_pred)
print("Train Accuracy: {:.4f}".format(train_acc))
print("Train F1 Score: {:.4f}".format(train_f1))

val_pred = linear_model.predict(val_features)
val_acc = accuracy_score(val_label, val_pred)
val_f1 = f1_score(val_label, val_pred)
print("Val Accuracy: {:.4f}".format(val_acc))
print("Val F1 Score: {:.4f}".format(val_f1))

print("Val Confusion Matrix: ")
tn, fp, fn, tp = confusion_matrix(val_label, val_pred).ravel()
print(confusion_matrix(val_label, val_pred))
print("Val False Discovery Rate: {:.4f}".format(fp/(fp+tn)))

test_pred = linear_model.predict(test_features)
test_acc = accuracy_score(test_label, test_pred)
test_f1 = f1_score(test_label, test_pred)
print("Test Accuracy: {:.4f}".format(test_acc))
print("Test F1 Score: {:.4f}".format(test_f1))

print("Test Confusion Matrix: ")
tn, fp, fn, tp = confusion_matrix(test_label, test_pred).ravel()
print(confusion_matrix(test_label, test_pred))
print("Test False Discovery Rate: {:.4f}".format(fp/(fp+tn)))

Train Accuracy: 0.6398
Train F1 Score: 0.7748
Val Accuracy: 0.2892
Val F1 Score: 0.4375
Val Confusion Matrix: 
[[  48 2648]
 [  11 1034]]
Val False Discovery Rate: 0.9822
Test Accuracy: 0.7284
Test F1 Score: 0.8411
Test Confusion Matrix: 
[[  31  861]
 [  32 2364]]
Test False Discovery Rate: 0.9652


In [12]:
kernel_lst = ['poly', 'rbf', 'sigmoid']
for kern in kernel_lst:
# test different kernel function SVM
    model = make_pipeline(StandardScaler(), SVC(kernel=kern))
    model.fit(train_features, train_label)
    # Prediction
    train_pred = model.predict(train_features)
    train_acc = accuracy_score(train_label, train_pred)
    train_f1 = f1_score(train_label, train_pred)
    print("Train Accuracy: {:.4f}".format(train_acc))
    print("Train F1 Score: {:.4f}".format(train_f1))

    val_pred = model.predict(val_features)
    val_acc = accuracy_score(val_label, val_pred)
    val_f1 = f1_score(val_label, val_pred)
    print("Val Accuracy: {:.4f}".format(val_acc))
    print("Val F1 Score: {:.4f}".format(val_f1))

    print("Val Confusion Matrix: ")
    tn, fp, fn, tp = confusion_matrix(val_label, val_pred).ravel()
    print(confusion_matrix(val_label, val_pred))
    print("Val False Discovery Rate: {:.4f}".format(fp/(fp+tn)))

    test_pred = model.predict(test_features)
    test_acc = accuracy_score(test_label, test_pred)
    test_f1 = f1_score(test_label, test_pred)
    print("Test Accuracy: {:.4f}".format(test_acc))
    print("Test F1 Score: {:.4f}".format(test_f1))

    print("Test Confusion Matrix: ")
    tn, fp, fn, tp = confusion_matrix(test_label, test_pred).ravel()
    print(confusion_matrix(test_label, test_pred))
    print("Test False Discovery Rate: {:.4f}".format(fp/(fp+tn)))

Train Accuracy: 0.6524
Train F1 Score: 0.7826
Val Accuracy: 0.2898
Val F1 Score: 0.4374
Val Confusion Matrix: 
[[  51 2645]
 [  12 1033]]
Val False Discovery Rate: 0.9811
Test Accuracy: 0.7235
Test F1 Score: 0.8375
Test Confusion Matrix: 
[[  37  855]
 [  54 2342]]
Test False Discovery Rate: 0.9585
Train Accuracy: 0.6625
Train F1 Score: 0.7855
Val Accuracy: 0.2927
Val F1 Score: 0.4361
Val Confusion Matrix: 
[[  72 2624]
 [  22 1023]]
Val False Discovery Rate: 0.9733
Test Accuracy: 0.7284
Test F1 Score: 0.8401
Test Confusion Matrix: 
[[  50  842]
 [  51 2345]]
Test False Discovery Rate: 0.9439
Train Accuracy: 0.5922
Train F1 Score: 0.7118
Val Accuracy: 0.3710
Val F1 Score: 0.4231
Val Confusion Matrix: 
[[ 525 2171]
 [ 182  863]]
Val False Discovery Rate: 0.8053
Test Accuracy: 0.6347
Test F1 Score: 0.7591
Test Confusion Matrix: 
[[ 195  697]
 [ 504 1892]]
Test False Discovery Rate: 0.7814
